// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// param
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of sat_bin_thr
//        bit 7~0 - sat_bin_thr[7:0] (Read/Write)
//        others  - reserved
// 0x14 : reserved
// 0x18 : Data signal of gray_bin_thr
//        bit 7~0 - gray_bin_thr[7:0] (Read/Write)
//        others  - reserved
// 0x1c : reserved
// 0x20 : Data signal of hist_hthr
//        bit 7~0 - hist_hthr[7:0] (Read/Write)
//        others  - reserved
// 0x24 : reserved
// 0x28 : Data signal of hist_lthr
//        bit 7~0 - hist_lthr[7:0] (Read/Write)
//        others  - reserved
// 0x2c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XPREIMPROC_PARAM_ADDR_SAT_BIN_THR_DATA  0x10
#define XPREIMPROC_PARAM_BITS_SAT_BIN_THR_DATA  8
#define XPREIMPROC_PARAM_ADDR_GRAY_BIN_THR_DATA 0x18
#define XPREIMPROC_PARAM_BITS_GRAY_BIN_THR_DATA 8
#define XPREIMPROC_PARAM_ADDR_HIST_HTHR_DATA    0x20
#define XPREIMPROC_PARAM_BITS_HIST_HTHR_DATA    8
#define XPREIMPROC_PARAM_ADDR_HIST_LTHR_DATA    0x28
#define XPREIMPROC_PARAM_BITS_HIST_LTHR_DATA    8

