// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xpreimproc.h"

extern XPreimproc_Config XPreimproc_ConfigTable[];

XPreimproc_Config *XPreimproc_LookupConfig(u16 DeviceId) {
	XPreimproc_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XPREIMPROC_NUM_INSTANCES; Index++) {
		if (XPreimproc_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XPreimproc_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XPreimproc_Initialize(XPreimproc *InstancePtr, u16 DeviceId) {
	XPreimproc_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XPreimproc_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XPreimproc_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

