// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xpreimproc.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPreimproc_CfgInitialize(XPreimproc *InstancePtr, XPreimproc_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Param_BaseAddress = ConfigPtr->Param_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPreimproc_Set_sat_bin_thr(XPreimproc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPreimproc_WriteReg(InstancePtr->Param_BaseAddress, XPREIMPROC_PARAM_ADDR_SAT_BIN_THR_DATA, Data);
}

u32 XPreimproc_Get_sat_bin_thr(XPreimproc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPreimproc_ReadReg(InstancePtr->Param_BaseAddress, XPREIMPROC_PARAM_ADDR_SAT_BIN_THR_DATA);
    return Data;
}

void XPreimproc_Set_gray_bin_thr(XPreimproc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPreimproc_WriteReg(InstancePtr->Param_BaseAddress, XPREIMPROC_PARAM_ADDR_GRAY_BIN_THR_DATA, Data);
}

u32 XPreimproc_Get_gray_bin_thr(XPreimproc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPreimproc_ReadReg(InstancePtr->Param_BaseAddress, XPREIMPROC_PARAM_ADDR_GRAY_BIN_THR_DATA);
    return Data;
}

void XPreimproc_Set_hist_hthr(XPreimproc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPreimproc_WriteReg(InstancePtr->Param_BaseAddress, XPREIMPROC_PARAM_ADDR_HIST_HTHR_DATA, Data);
}

u32 XPreimproc_Get_hist_hthr(XPreimproc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPreimproc_ReadReg(InstancePtr->Param_BaseAddress, XPREIMPROC_PARAM_ADDR_HIST_HTHR_DATA);
    return Data;
}

void XPreimproc_Set_hist_lthr(XPreimproc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPreimproc_WriteReg(InstancePtr->Param_BaseAddress, XPREIMPROC_PARAM_ADDR_HIST_LTHR_DATA, Data);
}

u32 XPreimproc_Get_hist_lthr(XPreimproc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPreimproc_ReadReg(InstancePtr->Param_BaseAddress, XPREIMPROC_PARAM_ADDR_HIST_LTHR_DATA);
    return Data;
}

