// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XPREIMPROC_H
#define XPREIMPROC_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xpreimproc_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Param_BaseAddress;
} XPreimproc_Config;
#endif

typedef struct {
    u32 Param_BaseAddress;
    u32 IsReady;
} XPreimproc;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XPreimproc_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XPreimproc_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XPreimproc_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XPreimproc_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XPreimproc_Initialize(XPreimproc *InstancePtr, u16 DeviceId);
XPreimproc_Config* XPreimproc_LookupConfig(u16 DeviceId);
int XPreimproc_CfgInitialize(XPreimproc *InstancePtr, XPreimproc_Config *ConfigPtr);
#else
int XPreimproc_Initialize(XPreimproc *InstancePtr, const char* InstanceName);
int XPreimproc_Release(XPreimproc *InstancePtr);
#endif


void XPreimproc_Set_sat_bin_thr(XPreimproc *InstancePtr, u32 Data);
u32 XPreimproc_Get_sat_bin_thr(XPreimproc *InstancePtr);
void XPreimproc_Set_gray_bin_thr(XPreimproc *InstancePtr, u32 Data);
u32 XPreimproc_Get_gray_bin_thr(XPreimproc *InstancePtr);
void XPreimproc_Set_hist_hthr(XPreimproc *InstancePtr, u32 Data);
u32 XPreimproc_Get_hist_hthr(XPreimproc *InstancePtr);
void XPreimproc_Set_hist_lthr(XPreimproc *InstancePtr, u32 Data);
u32 XPreimproc_Get_hist_lthr(XPreimproc *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
